"""initial migration

Revision ID: 22384f096717
Revises: 
Create Date: 2025-06-27 22:42:37.783517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22384f096717'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_updated_at'), ['updated_at'], unique=False)

    op.create_table('blood_pressure_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse_rate', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_pressure_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_pressure_record_timestamp'), ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_name'), ['user_name'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_file', sa.String(length=255), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_updated_at'), ['updated_at'], unique=False)

    op.create_table('patient_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('map', sa.Float(), nullable=False),
    sa.Column('pulse_pressure', sa.Float(), nullable=False),
    sa.Column('cholesterol', sa.Integer(), nullable=False),
    sa.Column('gluc', sa.Integer(), nullable=False),
    sa.Column('smoke', sa.Boolean(), nullable=False),
    sa.Column('alco', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('cardio', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_data_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('patient_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_profile_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_profile_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_profile_updated_at'))
        batch_op.drop_index(batch_op.f('ix_patient_profile_created_at'))

    op.drop_table('patient_profile')
    with op.batch_alter_table('patient_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_data_submitted_at'))

    op.drop_table('patient_data')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_updated_at'))
        batch_op.drop_index(batch_op.f('ix_models_name'))
        batch_op.drop_index(batch_op.f('ix_models_created_at'))

    op.drop_table('models')
    op.drop_table('document')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_full_name'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('blood_pressure_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_pressure_record_timestamp'))

    op.drop_table('blood_pressure_record')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_updated_at'))

    op.drop_table('device')
    # ### end Alembic commands ###
